### PR TITLE
refactor: provision-react-component

### PR DESCRIPTION
**Pull request by keithamus**
Did this for part of https://github.com/EconomistDigitalSolutions/fe-blogs/pull/75 - even though it ended up not being needed, thought I'd still PR it anyway

### CODE REVIEW

**Comment by umbobabo** [comment]
This is old. What is the current state? 
Can you solve the conflict and I will review this if you want.

**Comment by keithamus** [comment]
@umbobabo rebased.

**Comment by fabiosantoscode** [comment]
Looks like a :rainbow: from here, can you fix them conflicts, lest it gets forgotten?

**Comment by keithamus** [comment]
Another rebase. Perhaps we could merge this so I don't keep rebasing it :joy_cat:

**Comment by gcedo** [comment]
:+1: LGTM

**Pull request merged**
